language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
install: bundle install -j 4 --retry 3
script:
  - RAILS_ENV=test bundle exec rspec spec
services:
  - sqlite
